name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download a Build Artifact
      uses: actions/download-artifact@v8.0.1
      with:
        name: API em go

    - name: Login no Docker Hub
      run: echo "${{ secrets.PASSWORD_DOCKER_HUB }}" | docker login -u danilodamasceno --password-stdin

    - name: Build da imagem
      run: docker build -t danilodamasceno/curso-pipeline-docker:latest .

    - name: Push da imagem para o Docker Hub
      run: docker push danilodamasceno/curso-pipeline-docker:latest
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v7.3.0
      with:
        context: 
        file: ./Dockerfile
        push: true
        tags: danilodamasceno/go_ci:${{github.ref_name}}
    
     
