name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login no Docker Hub
      run: echo "${{ secrets.PASSWORD_DOCKER_HUB }}" | docker login -u danilodamasceno --password-stdin

    - name: Build da imagem
      run: docker build -t danilodamasceno/curso-pipeline-docker:latest .

    - name: Push da imagem para o Docker Hub
      run: docker push danilodamasceno/curso-pipeline-docker:latest
